# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

language: go

_addons: &addon_conf
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7-multilib
      - linux-libc-dev:i386

go:
  - "1.12"

git:
  depth: false

matrix:
  include:
    # newt build <targets>
    - os: linux
      env:
        - TEST=BUILD_TARGETS
        - VM_AMOUNT=1
        - TARGET_SET=1
#    - os: linux
#      env:
#        - TEST=BUILD_TARGETS
#        - VM_AMOUNT=4
#        - TARGET_SET=2
#    - os: linux
#      env:
#        - TEST=BUILD_TARGETS
#        - VM_AMOUNT=4
#        - TARGET_SET=3
#    - os: linux
#      env:
#        - TEST=BUILD_TARGETS
#        - VM_AMOUNT=4
#        - TARGET_SET=4

    # newt test all (Linux)
#    - os: linux
#      addons: *addon_conf
#      env:
#        - TEST=TEST_ALL
#        - VM_AMOUNT=3
#        - TARGET_SET=1
#    - os: linux
#      addons: *addon_conf
#      env:
#        - TEST=TEST_ALL
#        - VM_AMOUNT=3
#        - TARGET_SET=2
#    - os: linux
#      addons: *addon_conf
#      env:
#        - TEST=TEST_ALL
#        - VM_AMOUNT=3
#        - TARGET_SET=3

before_install:
  - printenv
  - export GOPATH=$HOME/gopath
  - go version

install:
  - git clone https://github.com/decawave/mynewt-travis-ci $HOME/ci
  - chmod +x $HOME/ci/*.sh
  - $HOME/ci/${TRAVIS_OS_NAME}_travis_install.sh

before_script:
  - newt version
  - gcc --version
  #- aarch64-linux-gnu-gcc --version
  - if [ "${TEST}" != "TEST_ALL" ]; then arm-none-eabi-gcc --version; fi
  - cp -R $HOME/ci/mynewt-dw1000-core-project.yml project.yml
  # Intentionally use the targets from the apps directory here too
  - cp -R $HOME/ci/mynewt-dw1000-apps-targets targets
  - newt install
    # Manually install the apps repo to avoid circular references
  - git clone https://github.com/decawave/mynewt-dw1000-apps repos/mynewt-dw1000-apps
  - sed -i "s/^#XX//g" project.yml
    # pass in the number of target sets
  - $HOME/ci/prepare_test.sh $VM_AMOUNT

    
script:
  - $HOME/ci/run_test.sh
    # Test arm64 dpl build
  - make generic && pushd ./build_generic;make; popd
  - make cortex-m3 && pushd ./build_cortex-m3;make; popd
  - make cortex-m4 && pushd ./build_cortex-m4;make; popd
  - make cortex-m7 && pushd ./build_cortex-m7;make; popd
  - make cortex-a73 && pushd ./build_cortex-a73;make; popd

cache:
  directories:
  - $HOME/TOOLCHAIN
  - $HOME/Library/Caches/Homebrew
